module_youtube = "YouTube"
mt_youtube = "Videos"
mt_youtube_up = "Like video"
yt_video_id = "YouTube video ID"
yt_url = "Video URL"
yt_title = "Title"
yt_description = "Description"
yt_channel = "Channel"
yt_thumbnail = "Thumbnail"
yt_vote_count = "Likes"
yt_vote_score = "Score"
